{
 "title": "Nginx Exporter Health Dashboard",
 "tags": [ "nginx" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Health check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "Status" }
   ]
  },
  {
   "title": "3. Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total[5m]))",
     "legendFormat": "Total requests/sec"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "Lost Connections ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nginx_connections_accepted - nginx_connections_handled",
     "legendFormat": "Total lost connections"
    }
   ]
  }
 ]
}